### ISSUE TITLE
Arena Enemy Frames

### ISSUE THREAD

**Issue by Stoney21** [Schaka/ArenaLive-WOTLK#3]
There are two bugs with them.
1. CC doesn't show up on class portraits most of the time.
2. DR indicator doesn't work for them.

**Comment by Schaka** [comment]
Could you update all the lists in spells.lua (then make a pull request, preferably) with WotLK spells and see if the issues persist?

**Comment by Stoney21** [comment]
Yeah, I'll do it and report later. That's the cause probably.
